version: "3.7"

services:
  map-mongo-db:
    image: mongo
    container_name: map-mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_PASSWORD=test
      - MONGO_USER=root
